### ISSUE TITLE
reply to woodghost

### ISSUE THREAD

**Issue by Jack614** [Jack614/jalpc_jekyll_theme#21]
@woodghost

**Comment by Jack614** [comment]
@woodghost 我的disqus现在打不开，在这里回复你的评论吧，public_key是在disqus申请的，你在disqus网站创建一个账号，然后为网站新建一个评论能够得到这个key。

**Comment by woodghost** [comment]
现在貌似不用key也可以了现在，我之前就没有生成过这个key

**Comment by Jack614** [comment]
去掉public_key也可以吗？我在帐号下生成的key有人评论可以收到邮件，在disqus后台可以管理评论

**Comment by Jack614** [comment]
@woodghost 期待你的网站完工，后面我首页加你的友情链接😊

**Comment by woodghost** [comment]
😊感谢大神的支持
