### ISSUE TITLE
Absolute path used at multiple places.

### ISSUE THREAD

**Issue by Prakhar0409** [Jack614/jalpc_jekyll_theme#26]
Hi, There have been multiple places where the code refers to absolute path. I have pointed out a few instances below.

1. `href="/blog/"` in index.html
2. `href="{{ post.url }}"` in blog/*.html
3. `src="/search/img/cb-button"` in blog/*.html

Since I am not sure of all the places where you used this type of naming, I am unable to correct them for myself. This kind of addressing poses problem in case I put my _site folder in some directory that is not '/' for the server. Could you please correct it. Thanks

**Comment by Jack614** [comment]
Hi,I find all the places are absolute path,the second written method you pointed out is syntax in `jekyll`, it is also absolute path,you can read documents about `jekyll` and understand it.
